### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by LeeBingler** [LeeBingler/ReactShop#12]
I need to create that file in order to help other to contribute to this project

**Comment by elidakirigo** [comment]
hi, I'd like to help you create that file where other contributors can be seen.

**Comment by LeeBingler** [comment]
I'm sorry but this file is not for that. This file will be created in order to give instruction on what to do to other user when they want to contribute on this project

**Comment by elidakirigo** [comment]
oh, I understand. i can help on that too
