### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by LeeBingler** [LeeBingler/Reactshop#4]
Write some test with vitest for all components

**Comment by elidakirigo** [comment]
hi, i'd also like to contribute in writing some tests in the components section

**Comment by LeeBingler** [comment]
You can work on it.
In order to test those React component i use Vitest and those test need to be in the Test directory at the root of the project.

**Comment by elidakirigo** [comment]
okay. thanks

**Comment by elidakirigo** [comment]
Hi @LeeBingler why'd you close it?.. I haven't gotten the chance to add a few more tests for other components
